version: 2
updates:
  # Enable version updates for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    # Check for updates once a week
    schedule:
      interval: "monthly"
