name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Setup ENV
        run: echo ::set-env name=TAG::$(echo ${GITHUB_REF:10})
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble jar with Gradle
        env:
          BUILD_NUMBER: ${{ steps.current-time.outputs.formattedTime }}
        run: ./gradlew clean assemble
      - name: Upload release assets
        id: upload-release-asset
        uses: AButler/upload-release-assets@v2.0
        with:
          release-tag: ${{ env.TAG }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: 'build/libs/*[!-dev].jar'
      - name: publish to GPR
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v2
        with:
          # Token used to authenticate with CurseForge API. Definitely use a secret for this.
          token: ${{ secrets.CF_API_TOKEN }}
          # Project id (numerical) to upload file to. You can ge the numerical ID from the sidebar on a project page.
          project_id: 391183
          # The subdomain of curseforge.com where the upload request will be made. (minecraft, kerbal, etc.)
          game_endpoint: minecraft
          # The path to the file you want to upload
          # The game version IDs to select on this file. Seperate IDs with "," (no quotes). You can specify numerical or slug/name IDs and they will be converted to numerical IDs. For slugs/names with duplicates, you can specify a type by prefixing the name/slug with "(type):" (no quotes). See README for more info.
          game_versions: 1.16.2,Fabric
          # The type of this release. Allowed values: alpha, beta, release
          release_type: beta


