name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Setup ENV
        run: echo ::set-env name=TAG::$(echo ${GITHUB_REF:10})
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble jar with Gradle
        env:
          BUILD_NUMBER: ${{ steps.current-time.outputs.formattedTime }}
        run: ./gradlew clean assemble
      - name: Upload release assets
        id: upload-release-asset
        uses: AButler/upload-release-assets@v2.0
        with:
          release-tag: ${{ env.TAG }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: 'build/libs/*[!-dev].jar'

      - name: Upload to curseforge
        id: upload_to_curse
        uses: itsmeow/curseforge-upload@master
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: 391183
          game_endpoint: minecraft
          file_path: build/libs/*[!-dev].jar
          changelog: (creator needs to make one)
          display_name: JARM-${{ env.TAG }}
          game_versions: 1.16-rc1, Java 8, Fabric
          release_type: alpha
          relations: fabric:dependency,